var $=jQuery;(function(a){a.fn.writeText=function(a){var c=a.split(""),d=0,e=this;setInterval(function(){d<c.length&&e.text(e.text()+c[d++])},100)}})(jQuery);function ltrim(a){return a?a.replace(/\s*((\S+\s*)*)/,"$1"):""}function rtrim(a){return a?a.replace(/((\s*\S+)*)\s*/,"$1"):""}function trim(a){return a?ltrim(rtrim(a)):""}
function entityEncode(a){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");a=a.replace(/  /g," &nbsp;");return a=/msie/i.test(navigator.userAgent)?a.replace("\n","&nbsp;<br />"):a.replace(/\x0D/g,"&nbsp;<br />")}
var TerminalShell={commands:{help:function(a){a.print($("<h3>"+wp_unix_i18n.help+"</h3>"));cmd_list=$("<ul>");$.each(this.commands,function(a){cmd_list.append($("<li>").text(a))});a.print(cmd_list)},clear:function(a){a.clear()}},filters:[],fallback:null,lastCommand:null,process:function(a,b){try{$.each(this.filters,$.proxy(function(c,d){b=d.call(this,a,b)},this));var c=b.split(" "),d=c.shift();c.unshift(a);this.commands.hasOwnProperty(d)?this.commands[d].apply(this,c):(!this.fallback||!this.fallback(a,
b))&&a.print($("<p>").addClass("error").text(wp_unix_i18n.bad_command));this.lastCommand=b}catch(e){a.print($("<p>").addClass("error").text("An internal error occurred: "+e)),a.setWorking(!1)}}},Terminal={buffer:"",pos:0,history:[],historyPos:0,promptActive:!0,cursorBlinkState:!0,_cursorBlinkTimeout:null,spinnerIndex:0,_spinnerTimeout:null,_specialKeys:{17:"ctrl",18:"alt",145:"scroll"},output:TerminalShell,config:{scrollStep:20,scrollSpeed:100,bg_color:"#000",fg_color:"#00FF44",cursor_blink_time:700,
cursor_style:"block",prompt:wp_unix_i18n.prompt,spinnerCharacters:["[   ]","[.  ]","[.. ]","[...]"],spinnerSpeed:250,typingSpeed:25},sticky:{keys:{ctrl:!1,alt:!1,scroll:!1},set:function(a,b){this.keys[a]=b;$("#"+a+"-indicator").toggle(this.keys[a])},toggle:function(a){this.set(a,!this.keys[a])},reset:function(a){this.set(a,!1)},resetAll:function(){$.each(this.keys,$.proxy(function(a){this.reset(a)},this))}},init:function(){function a(a){return function(){Terminal.promptActive&&a.apply(this,arguments)}}
$(document).keypress($.proxy(a(function(a){if(32<=a.which&&126>=a.which){var c=String.fromCharCode(a.which),d=c.toLowerCase();if(!$.browser.opera||/[\w\s]/.test(c))this.sticky.keys.ctrl?"w"==d?this.deleteWord():"h"==d?Terminal.deleteCharacter(!1):"l"==d?this.clear():"a"==d?this.setPos(0):"e"==d?this.setPos(this.buffer.length):"d"==d&&this.runCommand("logout"):c&&(this.addCharacter(c),a.preventDefault())}}),this));$.hotkeys.add("return",a(function(){Terminal.processInputBuffer()}));$.hotkeys.add("backspace",
a(function(a){a.preventDefault();Terminal.deleteCharacter(a.shiftKey)}));$.hotkeys.add("del",a(function(){Terminal.deleteCharacter(!0)}));$.hotkeys.add("left",a(function(){Terminal.moveCursor(-1)}));$.hotkeys.add("right",a(function(){Terminal.moveCursor(1)}));$.hotkeys.add("up",a(function(a){a.preventDefault();a.shiftKey||Terminal.sticky.keys.scroll?Terminal.scrollLine(-1):a.ctrlKey||Terminal.sticky.keys.ctrl?Terminal.scrollPage(-1):Terminal.moveHistory(-1)}));$.hotkeys.add("down",a(function(a){a.preventDefault();
a.shiftKey||Terminal.sticky.keys.scroll?Terminal.scrollLine(1):a.ctrlKey||Terminal.sticky.keys.ctrl?Terminal.scrollPage(1):Terminal.moveHistory(1)}));$.hotkeys.add("pageup",a(function(){Terminal.scrollPage(-1)}));$.hotkeys.add("pagedown",a(function(){Terminal.scrollPage(1)}));$.hotkeys.add("home",a(function(a){a.preventDefault();a.ctrlKey||Terminal.sticky.keys.ctrl?Terminal.jumpToTop():Terminal.setPos(0)}));$.hotkeys.add("end",a(function(a){a.preventDefault();a.ctrlKey||Terminal.sticky.keys.ctrl?
Terminal.jumpToBottom():Terminal.setPos(Terminal.buffer.length)}));$.hotkeys.add("tab",function(a){a.preventDefault()});$(document).keyup(function(a){a=Terminal._specialKeys[a.which];a in{ctrl:!0,alt:!0,scroll:!0}?Terminal.sticky.toggle(a):a in{left:!0,right:!0,up:!0,down:!0}||Terminal.sticky.resetAll()});$(window).resize(function(){$("#screen").scrollTop($("#screen").attr("scrollHeight"))});this.setCursorState(!0);this.setWorking(!1);$("#prompt").html(this.config.prompt);$("#screen").hide().fadeIn("fast",
function(){$("#screen").triggerHandler("cli-load")})},setCursorState:function(a,b){this.cursorBlinkState=a;"block"==this.config.cursor_style?a?$("#cursor").css({color:this.config.bg_color,backgroundColor:this.config.fg_color}):$("#cursor").css({color:this.config.fg_color,background:"none"}):a?$("#cursor").css("textDecoration","underline"):$("#cursor").css("textDecoration","none");!b&&this._cursorBlinkTimeout&&(window.clearTimeout(this._cursorBlinkTimeout),this._cursorBlinkTimeout=null);this._cursorBlinkTimeout=
window.setTimeout($.proxy(function(){this.setCursorState(!this.cursorBlinkState,true)},this),this.config.cursor_blink_time)},updateInputDisplay:function(){var a="",b=" ",c="";0>this.pos&&(this.pos=0);this.pos>this.buffer.length&&(this.pos=this.buffer.length);0<this.pos&&(a=this.buffer.substr(0,this.pos));this.pos<this.buffer.length&&(b=this.buffer.substr(this.pos,1));1<this.buffer.length-this.pos&&(c=this.buffer.substr(this.pos+1,this.buffer.length-this.pos-1));$("#lcommand").text(a);$("#cursor").text(b);
" "==b&&$("#cursor").html("&nbsp;");$("#rcommand").text(c);$("#prompt").text(this.config.prompt)},clearInputBuffer:function(){this.buffer="";this.pos=0;this.updateInputDisplay()},clear:function(){$("#display").html("")},addCharacter:function(a){var b=this.buffer.substr(0,this.pos),c=this.buffer.substr(this.pos,this.buffer.length-this.pos);this.buffer=b+a+c;this.pos++;this.updateInputDisplay();this.setCursorState(!0)},deleteCharacter:function(a){a=a?1:0;if(this.pos>=1-a){var b=this.buffer.substr(0,
this.pos-1+a),c=this.buffer.substr(this.pos+a,this.buffer.length-this.pos-a);this.buffer=b+c;this.pos-=1-a;this.updateInputDisplay()}this.setCursorState(!0)},deleteWord:function(){if(0<this.pos){for(var a=this.pos;0<a&&" "!==this.buffer.charAt(a);)a--;left=this.buffer.substr(0,a-1);right=this.buffer.substr(a,this.buffer.length-this.pos);this.buffer=left+right;this.pos=a;this.updateInputDisplay()}this.setCursorState(!0)},moveCursor:function(a){this.setPos(this.pos+a)},setPos:function(a){0<=a&&a<=this.buffer.length&&
(this.pos=a,Terminal.updateInputDisplay());this.setCursorState(!0)},moveHistory:function(a){a=this.historyPos+a;0<=a&&a<=this.history.length&&(a==this.history.length?this.clearInputBuffer():this.buffer=this.history[a],this.pos=this.buffer.length,this.historyPos=a,this.updateInputDisplay(),this.jumpToBottom());this.setCursorState(!0)},addHistory:function(a){this.historyPos=this.history.push(a)},jumpToBottom:function(){$("#screen").scrollTop($("#screen").prop("scrollHeight"))},jumpToTop:function(){$("#screen").scrollTop(0)},
scrollPage:function(a){$("#screen").scrollTop($("#screen").scrollTop()+a*0.75*$("#screen").height())},scrollLine:function(a){$("#screen").scrollTop($("#screen").scrollTop()+a*this.config.scrollStep)},print:function(a){if(a)if(a instanceof jQuery)$("#display").append(a);else{var b=Array.prototype.slice.call(arguments,0);$("#display").append($("<p>").text(b.join(" ")))}else $("#display").append($("<div>"));this.jumpToBottom()},processInputBuffer:function(a){this.print($("<p>").addClass("command").text(this.config.prompt+
this.buffer));a=trim(this.buffer);this.clearInputBuffer();if(0==a.length)return!1;this.addHistory(a);return this.output?this.output.process(this,a):!1},setPromptActive:function(a){this.promptActive=a;$("#inputline").toggle(this.promptActive)},setWorking:function(a){a&&!this._spinnerTimeout?($("#display .command:last-child").add("#bottomline").first().append($("#spinner")),this._spinnerTimeout=window.setInterval($.proxy(function(){$("#spinner").is(":visible")||$("#spinner").fadeIn();this.spinnerIndex=
(this.spinnerIndex+1)%this.config.spinnerCharacters.length;$("#spinner").text(this.config.spinnerCharacters[this.spinnerIndex])},this),this.config.spinnerSpeed),this.setPromptActive(!1),$("#screen").triggerHandler("cli-busy")):!a&&this._spinnerTimeout&&(clearInterval(this._spinnerTimeout),this._spinnerTimeout=null,$("#spinner").fadeOut(),this.setPromptActive(!0),$("#screen").triggerHandler("cli-ready"))},runCommand:function(a){var b=0;this.promptActive=!1;var c=window.setInterval($.proxy(function(){b<
a.length?(this.addCharacter(a.charAt(b)),b+=1):(clearInterval(c),this.promptActive=!0,this.processInputBuffer())},this),this.config.typingSpeed)}};TerminalShell.commands.restart=function(a){this.sudo?(TerminalShell.process(a,"sudo shutdown"),setTimeout(function(){document.location.reload()},1500)):a.print($("<p>").addClass("error").text("Must be root"))};
TerminalShell.commands.shutdown=function(a){this.sudo?(username=a.config.prompt.split(":",1),a.print("Broadcast message from "+username[0]+":"),a.print(),a.print("The system is going down for maintenance NOW!"),$("#prompt, #cursor").hide(),a.promptActive=!1,$("#screen").delay(1E3).fadeOut("slow")):a.print($("<p>").addClass("error").text("Must be root"))};
TerminalShell.commands.sudo=function(a){var b=Array.prototype.slice.call(arguments);b.shift();if("make me a sandwich"==b.join(" "))a.print("Okay.");else{var c=b.shift();b.unshift(a);b.push("sudo");TerminalShell.commands.hasOwnProperty(c)?(this.sudo=!0,this.commands[c].apply(this,b),delete this.sudo):c?a.print("sudo: "+c+": command not found"):a.print("sudo what?")}};
TerminalShell.commands.logout=TerminalShell.commands.exit=TerminalShell.commands.quit=function(a){a.print("Bye.");$("#prompt, #cursor").hide();a.promptActive=!1};TerminalShell.commands.source=function(a){a.print($("<a>").attr("href","https://github.com/benbalter/wordpress-unix-theme").text("https://github.com/benbalter/wordpress-unix-theme"))};
$(document).ready(function(){$("#welcome").show();document.onkeydown=document.onkeypress=function(a){return"backspace"!=$.hotkeys.special_keys[a.keyCode]};Terminal.init()});